"""empty message

Revision ID: 10918c8a2e0e
Revises: aeca425ec920
Create Date: 2020-10-21 21:03:19.404792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10918c8a2e0e'
down_revision = 'aeca425ec920'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'ShowType')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('ShowType', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
